[programs.localnet]
whirlpool = "4ERwQLtitCdCvSqjzrrVUTeZNfisLNuo3J8HVrbo6mn6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# wait for update to anchor to support cloning
# [[test.genesis]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
# program = "../metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

[scripts]
test = "yarn ts-mocha -p sdk/tests/tsconfig.json -t 1000000 sdk/tests/integration/two_hop_swap_with_fee_discount.test.ts"
