
  export const poolEnv = {
    TOKEN_MINT_A: "3JVvARFtkKwF6X8HQvt2GTTGsmaranqMk7YCn5RX7HG5",
    TOKEN_MINT_B: "4TMYXv2BNSb5PSFw2aYWk6rB4ERui8gYbbkRU81gLD3b",
    TICK_SPACING: 32,
    INIT_AMOUNT_B_PER_A: "10",
    LOWER_B_PER_A_PRICE: "1",
    UPPER_B_PER_A_PRICE: "100",
    SLIPPAGE: "1",
    INPUT_MINT: "3JVvARFtkKwF6X8HQvt2GTTGsmaranqMk7YCn5RX7HG5",
    INPUT_AMOUNT: "1000",
  };
    